### ISSUE TITLE
mf2005 fails to generate output on macOS Monterey

### ISSUE THREAD

**Issue by OliverSchmitz** [MODFLOW-USGS/mf2005#50]
Hi,
I compiled for macOS (both x86_64 and arm64) but the executable fails to generate output. I added `CALL FLUSH()` at the end of mf2005.f as described here https://github.com/modflowpy/pymake/issues/97, that resolves the problem.
Just in case someone else stumbles over this...
Cheers,
Oliver

**Comment by jdhughes-dev** [comment]
@OliverSchmitz Would you care to add your change as a pull request?
